name: Build and Share Docker Image

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Build Docker image and save as tar
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t my-simple-image .

      - name: Save Docker image to tar file
        run: docker save my-simple-image -o my-simple-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: my-simple-image.tar

  # Step 2: Download and use the Docker image
  load:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the 'build' job
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image from tar file
        run: docker load -i my-simple-image.tar

      - name: Run the Docker container
        run: docker run my-simple-image
